language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm install
  - CI=false npm run build
deploy:
  provider: pages
  skip_cleanup: true
  target_branch: master
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: dev
